name: 
  Run server on push

on:
  push

jobs:
  run_django_server:
    runs-on: 
      ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove sqlite3 db
        run: |
          find . -name "*.sqlite3" -type f -delete

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r windows_requirements.txt

      - name: Run Tests
        run: |
          python manage.py makemigrations
          1
          1
          python manage.py migrate
          pytest -s