name: 
  Run server on push

on:
  push

jobs:
  run_migrations:
    runs-on: 
      ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove sqlite3 db and migrations files
        run: |
          find . -name "*.sqlite3" -type f -delete
          find . -path "*/migrations/*.py" -name "*.py" ! -name "__init__.py" -type f -delete

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r windows_requirements.txt

      - name: Run Tests and Migrations
        run: |
          python manage.py check
          python manage.py makemigrations
          python manage.py migrate
  
  run_tests: 
    needs: run_migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 
            '3.14'
      
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r windows_requirements.txt
      
      - name: Run tests
        run: |
          pytest -s

  lint_python_code:
    runs-on: ubuntu-latest
    needs: [run_migrations]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 
            '3.14'
      
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r windows_requirements.txt
      
      - name: Lint python code
        run: |
          flake8 .
